### PR TITLE
Approaches For Building An App

### PR DESCRIPTION
**Pull request by matthewjjohnsen**
@bmash725 @lhh421 @jarjarbinksbinks @vinnyv27 Please take a look and provide any feedback!

### CODE REVIEW

**Comment by vinnyv27** [comment]
@matthewjjohnsen I'd suggest adding a quick sentence about what native / cross-platform / hybrid actually are before jumping into the pros and cons.

**Comment by jarjarbinksbinks** [comment]
@matthewjjohnsen Well done - and the image you found is spot on

**Comment by lhh421** [comment]
@matthewjjohnsen Great content!  I suggest adding another Con under "Native App"  - need to constantly modify and support the latest as iOS / Android / Windows / Blackberry OS goes through version upgrades.

**Comment by matthewjjohnsen** [comment]
@vinnyv27 @bmash725 @lhh421 @jarjarbinksbinks I have incorporate all comments. Can I get a :+1: so we can :ship: it?

**Comment by lhh421** [comment]
-   LGTM :+1: Let’s :ship: it

**Comment by bmash725** [comment]
@matthewjjohnsen LGTM :+1: Let's :ship: it!

**Pull request merged**
