### PR TITLE
Ways to Source Software Developers for Hire

### PR DESCRIPTION
**Pull request by bmash725**
Here you can find a list of numerous ways to source software developers for hire, including some helpful links.

### CODE REVIEW

**Comment by bmash725** [comment]
@lhh421 @jarjarbinksbinks @matthewjjohnsen @vinnyv27 please let me know if you have any feedback on this or if you would like anything to be updated.  Thanks!

**Comment by jarjarbinksbinks** [comment]
@bmash725 - Noticed a spelling error in the second bullet. "Pesonal"

**Comment by lhh421** [comment]
@bmash725 Great comprehensive list! Perhaps worth it to add a line explicitly about sourcing developers through agencies? Mention something along the way of "easier to source larger group," and "insurance against unexpected interruptions"

**Comment by bmash725** [comment]
Thanks for the feedback @jarjarbinksbinks @lhh421 @matthewjjohnsen @vinnyv27 .  Does everything look good?  Can I have a :+1: to ship from each of you?

**Comment by lhh421** [comment]
-   LGTM :+1: Let’s :ship: it

**Comment by matthewjjohnsen** [comment]
@bmash725 LGTM :+1: Let’s :ship: it

**Pull request merged**
