### PR TITLE
Implications of Orthogonailty

### PR DESCRIPTION
**Pull request by vinnyv27**
@jarjarbinksbinks @lhh421 @bmash725 @matthewjjohnsen please add your comments!

### CODE REVIEW

**Comment by bmash725** [comment]
@vinnyv27 this is an extremely detailed description.  Well done!  One slight piece of feedback.  In the last bullet, can you briefly mention what the "no broken windows" rule actually is?  There is a great description on this website, which has text taken from "The Pragmatic Programmer": https://pragprog.com/the-pragmatic-programmer/extracts/software-entropy

**Comment by lhh421** [comment]
@vinnyv27 Very nicely organized article!  It is implied already, but perhaps worth it to mention in your second bullet regarding knowledge transfer if a programmer leaves that, orthogonality is also advantageous when only making a updates to a small component of the overall program.

**Comment by vinnyv27** [comment]
@bmash725 @lhh421 @jarjarbinksbinks @matthewjjohnsen thanks for the suggestions I've incorporated your changes

**Comment by lhh421** [comment]
@vinnyv27 - LGTM :+1: Let’s :ship: it

**Comment by bmash725** [comment]
@vinnyv27 LGTM as well :+1: Let's :ship: it!

**Pull request merged**
