### PR TITLE
Create Popular-Languages

### PR DESCRIPTION
**Pull request by jarjarbinksbinks**
My piece on popular programming languages

### CODE REVIEW

**Comment by jarjarbinksbinks** [comment]
@vinnyv27  @lhh421 @bmash725 @matthewjjohnsen please add your comments! 

How do I make the nice formatting like you guys did?

**Comment by matthewjjohnsen** [comment]
Ben, this looks good. Regarding your question of how to make the formatting nice, you need to save the file by ending the file name with ".md", but it looks like you just figured this out.

**Comment by bmash725** [comment]
@jarjarbinksbinks this is extremely informative.  Can you also briefly mention what "front-end" and "back-end" mean?  For example, what each would be used for.  Thanks!

**Comment by vinnyv27** [comment]
@jarjarbinksbinks love the image & the detail on front end languages. Can you add any detail to the back-end languages?

**Comment by lhh421** [comment]
@jarjarbinksbinks Nice and concise.  Maybe worth it to specify that these are popular front end development languages for webpages specifically, on the title?

**Comment by bmash725** [comment]
@jarjarbinksbinks time is of the essence.  Therefore, this is acceptable and :+1: and ready to :ship:

**Comment by lhh421** [comment]
LGTM :+1: Let’s :ship: it

**Pull request merged**
